name: Build and Push Agent Image
on:
  push:
    tags:
      - 'release-*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Fixed for BeeAI SDK compatibility
    - name: Install BeeAI CLI
      run: pip install beeai-cli
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract version from tag
      id: extract_version
      run: |
        # Extract version from tag (e.g., release-0.0.10 -> 0.0.10)
        VERSION=${GITHUB_REF#refs/tags/release-}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Build and Push
      run: |
        beeai build ./ --tag ghcr.io/${{ github.repository }}/granite_chat_agent:${{ steps.extract_version.outputs.version }} --no-import --multi-platform --push
