name: Build and Push Agent Image
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.x'
    - name: Install BeeAI CLI
      run: pip install beeai-cli==0.3.0rc8
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker
      uses: docker/setup-docker-action@v4
      with:
        daemon-config: '{"features": {"containerd-snapshotter": true}}'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Extract version from tag
      id: extract_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Build and Push
      run: |
        beeai build ./ --tag ghcr.io/${{ github.repository }}/granite_chat_agent:${{ steps.extract_version.outputs.version }} --no-import --multi-platform --push